apiVersion: v1
kind: Pod
metadata:
  name: pg-debug
spec:
  containers:
    - name: debug
      image: debian:bookworm-slim
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql
  volumes:
    - name: pgdata
      persistentVolumeClaim:
        claimName: postgres-volume-claim
